about/urls.py
from django.urls import path

from about import views

app_name = 'about'

urlpatterns = [
    path('', views.about, name='about'),
]

api/urls.py
from django.urls import include, path
from rest_framework.urlpatterns import format_suffix_patterns

from api.views import api_root
from products.views import (ProductListCreateAPIView,
                            ProductRetrieveUpdateDestroyAPIView)
from stores.views import (StoreListCreateAPIView,
                          StoreRetrieveUpdateDestroyAPIView)

urlpatterns = [
    path('', api_root, name='api-root'),
    path('products/', include([
        path('', ProductListCreateAPIView().as_view(), name='products-list'),
        path('<int:pk>/', ProductRetrieveUpdateDestroyAPIView().as_view(),
             name='products-detail')
    ])),
    path('stores/', include([
        path('', StoreListCreateAPIView().as_view(), name='stores-list'),
        path('<int:pk>', StoreRetrieveUpdateDestroyAPIView().as_view(),
             name='stores-detail')
    ]))
]

urlpatterns = format_suffix_patterns(urlpatterns)

app/urls.py
from django.urls import path

from app import views

app_name = 'app'

urlpatterns = [
    path('', views.app_install, name='app_install'),
]

digital_showcase/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('mall/', include('stores.urls')),
    path('about/', include('about.urls')),
    path('newsletter/', include('newsletter.urls')),
    path('showcase/', include('showcase.urls')),
    path('customers/', include('customers.urls')),
    path('app/', include('app.urls')),
    path('api/', include('api.urls')),
    path('api-auth/', include('rest_framework.urls')),
    path('', RedirectView.as_view(url='mall/')),
    path('', include('pwa_fix.urls'))
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

newsletter/urls.py
from django.urls import path

from newsletter import views

app_name = 'newsletter'

urlpatterns = [
    path('', views.subscribe, name='newsletter'),
    path('validate-subscribe/', views.validate_subscribe,
         name='validate_subscribe')
]

showcase/urls.py
from django.urls import path

from showcase import views

app_name = 'showcase'

urlpatterns = [
    path('<slug:slug>/', views.ShowcaseDetailView.as_view(), name='showcase')
]

stores/urls.py
from django.urls import path

from stores import views

app_name = 'stores'

urlpatterns = [
    path('', views.StoresListView.as_view(), name='choose-store')
]

stores/models.py
from django.core.exceptions import ValidationError
from django.db import models
from validate_docbr import CNPJ

from customers.models import Adresses, Emails, Phones
from global_models.models import SocialNetworks


class Stores(models.Model):

    class GroupChoices(models.TextChoices):
        COSMETICS = 'Cosméticos', 'Cosméticos'
        CANDY = 'Doceria', 'Doceria'
        SNACK_BAR = 'Lanchonete', 'Lanchonete'
        PIZZERIA = 'Pizzaria', 'Pizzaria'
        RESTAURANT = 'Restaurante', 'Restaurante'
        CLOTHING = 'Vestuário', 'Vestuário'

    def validate_cnpj(value):
        if not CNPJ().validate(value):
            raise ValidationError('CNPJ inválido.')

    cnpj = models.CharField(verbose_name='CNPJ',
                            max_length=14,
                            validators=[validate_cnpj],
                            primary_key=True,
                            unique=True)

    business_name = models.CharField(verbose_name='Razão Social',
                                     max_length=100)

    title_establishment = models.CharField(verbose_name='Fantasia',
                                           max_length=30,
                                           unique=True)

    group = models.CharField(verbose_name='Grupo',
                             choices=GroupChoices.choices,
                             max_length=15)

    address = models.ManyToManyField(Adresses,
                                     verbose_name='Endereço',
                                     blank=True)

    address_number = models.PositiveIntegerField(verbose_name='Número',
                                                 blank=True,
                                                 null=True)

    address_complement = models.CharField(verbose_name='Complemento',
                                          max_length=120,
                                          blank=True,
                                          null=True)

    phones = models.ManyToManyField(Phones,
                                    verbose_name='Telefones',
                                    blank=True)

    emails = models.ManyToManyField(Emails,
                                    verbose_name='E-mails',
                                    blank=True)

    social_networks = models.ManyToManyField(SocialNetworks,
                                             verbose_name='Redes Sociais',
                                             blank=True)

    slug = models.SlugField(verbose_name='Slug',
                            max_length=30,
                            unique=True)

    active = models.BooleanField(verbose_name='Ativa',
                                 default=True)

    logo = models.ImageField(blank=True,
                             null=True,
                             upload_to='stores_images/',
                             verbose_name='Logotipo')

    recorded = models.DateTimeField(verbose_name='Gravado em',
                                    auto_now_add=True)

    updated = models.DateTimeField(verbose_name='Atualizado em',
                                   auto_now=True)

    class Meta:
        ordering = ['business_name']
        verbose_name = 'Loja'
        verbose_name_plural = 'Lojas'

    def __str__(self):
        return self.business_name

stores/forms.py
from django import forms
from django.utils.text import slugify

from stores.models import Stores


class StoresForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super(StoresForm, self).__init__(*args, **kwargs)

        self.fields['cnpj'].widget.attrs['class'] += ' vMaskCnpjField'
        self.fields['slug'].widget.attrs['readonly'] = True

    def clean_slug(self):
        data = self.cleaned_data['slug']

        if 'title_establishment' in self.cleaned_data:
            data = slugify(self.cleaned_data['title_establishment'])

        return data

    class Meta:
        model = Stores
        fields = '__all__'

stores/views.py
from django.conf import settings
from django.contrib import messages
from django.views.generic import ListView
from rest_framework.generics import (ListCreateAPIView,
                                     RetrieveUpdateDestroyAPIView)
from rest_framework.permissions import IsAuthenticatedOrReadOnly

from stores.models import Stores
from stores.serializers import StoreHyperlinkedSerializer, StoreSerializer


class StoresListView(ListView):
    context_object_name = 'stores'
    template_name = 'stores/choose-store.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['group_stores_images'] = settings.GROUP_STORES_IMAGES
        return context

    def get_queryset(self):
        queryset = Stores.objects.filter(active=True)

        if not queryset:
            msg_empty_stores = 'Lamentamos mas ainda não há lojas cadastradas!'
            messages.add_message(self.request, messages.INFO, msg_empty_stores)

        return queryset


class StoreListCreateAPIView(ListCreateAPIView):

    queryset = Stores.objects.all()
    serializer_class = StoreHyperlinkedSerializer
    permission_classes = [IsAuthenticatedOrReadOnly]


class StoreRetrieveUpdateDestroyAPIView(RetrieveUpdateDestroyAPIView):

    queryset = Stores.objects.all()
    serializer_class = StoreSerializer
    permission_classes = [IsAuthenticatedOrReadOnly]

stores/templates/stores/choose-store.html
{% extends "base/index.html" %}

{% load static %}

{% block "style" %}
    <link rel="stylesheet" type="text/css" href="{% static 'stores/css/store-stylesheet.css' %}">
{% endblock %}

{% block "title" %}Vitrine Digital{% endblock %}

{% block "nav_items" %}
    <li class="nav-item"><a href="{% url 'stores:choose-store' %}" class="nav-link active">Início</a></li>
    <li class="nav-item"><a href="{% url 'newsletter:newsletter' %}" class="nav-link">Newsletter</a></li>
    <li class="nav-item"><a href="{% url 'app:app_install' %}" class="nav-link" aria-current="page">Nosso App</a></li>
    <li class="nav-item"><a href="{% url 'about:about' %}" class="nav-link" aria-current="page">Sobre</a></li>
{% endblock %}

{% block "body" %}
    <!-- Inclusion of Bootstrap alert messages -->
    {% include "base/message.html" %}

    <!-- Showcase - Slogan -->
    <div class="hero-image position-relative" style="background-image: url('{% static "img/showcase-slogan3.png" %}');"></div>
    
    <!-- Information banner -->
    <div class="container-fluid d-flex justify-content-center bg-info-banner text-white p-4 gap-3">
        <div class="d-flex align-items-center pt-1">
            <span class="material-symbols-rounded fs-1 text-shadow-1 m-0">local_mall</span>
        </div>
        <h4 class="display-4 m-0 fw-light text-shadow-1">O melhor da região na sua vitrine</h4>
    </div>
    
    <!-- Bootstrap cards to represent participating stores -->
    {% if stores %}
        {% if stores|length == 1 %}
            {% for store in stores %}
                <meta http-equiv="REFRESH" content="0;url={% url 'showcase:showcase' slug=store.slug %}">
            {% endfor %}
        {% else %}
            <div class="container-fluid p-4">
                <div class="row row-cols-1 row-cols-sm-2 row-cols-md-2 row-cols-lg-3 align-items-stretch g-4">
                    {% for store in stores %}
                        {% include "stores/store-cards.html" %}
                    {% endfor %}
                </div>
            </div>
        {% endif %}
    {% endif %}

    <!-- Newsletter subscription section  -->
    {% include "stores/store_newsletter.html" %}
{% endblock %}

<!-- {% block "social_media" %}{% endblock %} -->

{% block "script" %}
    <script src="{% static 'js/modal.alert.js' %}"></script>
{% endblock %}

stores/templates/stores/store-cards.html
{% load static %}

{% for key, value in group_stores_images.items %}
    {% if key == store.group %}
        <div class="col">
            <a class="text-decoration-none" href="{% url 'showcase:showcase' slug=store.slug %}">
                <div class="store-card card card-cover h-100 overflow-hidden text-primary text-shadow-1 rounded-5 shadow-lg" 
                    style="background-image: url('{% static value.0 %}');">
                    <div class="d-flex flex-column h-100 p-5 pb-3">
                        <h6 class="pt-5 mt-5 mb-4 display-6 lh-1 fw-bold">{{ store.title_establishment }}</h6>
                        
                        <ul class="d-flex list-unstyled mt-auto flex-row-reverse">
                            <li class="d-flex align-items-center gap-1">
                                <span class="material-symbols-rounded">{{ value.1 }}</span>
                                <small>{{ store.group }}</small>
                            </li>
                        </ul>
                    </div>
                </div>
            </a>
        </div>
    {% endif %}
{% endfor %}

stores/templates/stores/store_newsletter.html
{% load static %}

<div class="container px-4 my-5">
    <div class="row row-cols-1 row-cols-md-1 row-cols-lg-2 flex-row-reverse align-items-center g-5">
        
        <div class="col">
            <img src="{% static 'stores/img/newsletter.jpg' %}" class="d-block mx-lg-auto img-fluid" alt="Imagem da Newsletter" loading="lazy">
        </div>
        
        <div class="col">
            <h1 class="display-5 fw-bold lh-1 mb-3">Assine nossa newsletter</h1>
            <p class="lead">Para ficar por dentro de todas as novidades e lançamentos, as melhores ofertas e promoções, assine nossa newsletter e receba no conforto de seu lar todas essas vantagens. Clique agora mesmo em inscrever-se!</p>
            <div class="d-grid gap-2 d-md-flex justify-content-md-start">
                <a href="{% url 'newsletter:newsletter' %}" class="btn btn-primary btn-lg px-4 me-md-2" role="button">Inscrever-se</a>
            </div>
        </div>

    </div>
</div>