about/urls.py
from django.urls import path

from about import views

app_name = 'about'

urlpatterns = [
    path('', views.about, name='about'),
]

api/urls.py
from django.urls import include, path
from rest_framework.urlpatterns import format_suffix_patterns

from api.views import api_root
from products.views import (ProductListCreateAPIView,
                            ProductRetrieveUpdateDestroyAPIView)
from stores.views import (StoreListCreateAPIView,
                          StoreRetrieveUpdateDestroyAPIView)

urlpatterns = [
    path('', api_root, name='api-root'),
    path('products/', include([
        path('', ProductListCreateAPIView().as_view(), name='products-list'),
        path('<int:pk>/', ProductRetrieveUpdateDestroyAPIView().as_view(),
             name='products-detail')
    ])),
    path('stores/', include([
        path('', StoreListCreateAPIView().as_view(), name='stores-list'),
        path('<int:pk>', StoreRetrieveUpdateDestroyAPIView().as_view(),
             name='stores-detail')
    ]))
]

urlpatterns = format_suffix_patterns(urlpatterns)

app/urls.py
from django.urls import path

from app import views

app_name = 'app'

urlpatterns = [
    path('', views.app_install, name='app_install'),
]

digital_showcase/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('mall/', include('stores.urls')),
    path('about/', include('about.urls')),
    path('newsletter/', include('newsletter.urls')),
    path('showcase/', include('showcase.urls')),
    path('customers/', include('customers.urls')),
    path('app/', include('app.urls')),
    path('api/', include('api.urls')),
    path('api-auth/', include('rest_framework.urls')),
    path('', RedirectView.as_view(url='mall/')),
    path('', include('pwa_fix.urls'))
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

newsletter/urls.py
from django.urls import path

from newsletter import views

app_name = 'newsletter'

urlpatterns = [
    path('', views.subscribe, name='newsletter'),
    path('validate-subscribe/', views.validate_subscribe,
         name='validate_subscribe')
]

stores/urls.py
from django.urls import path

from stores import views

app_name = 'stores'

urlpatterns = [
    path('', views.StoresListView.as_view(), name='choose-store')
]

newsletter/models.py
from django.db import models


class Newsletter(models.Model):

    name = models.CharField(verbose_name='Nome completo',
                            max_length=100)

    email = models.EmailField(verbose_name='E-mail',
                              primary_key=True,
                              unique=True)

    signed = models.DateTimeField(verbose_name='Assinado em',
                                  auto_now=True,
                                  editable=False)

    class Meta:
        ordering = ['name']
        verbose_name = 'Boletim Informativo'
        verbose_name_plural = 'Boletins Informativos'

    def __str__(self):
        return self.email

newsletter/forms.py
from django import forms
from utils.tools import string_capitalize

from newsletter.models import Newsletter


class NewsletterForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super(NewsletterForm, self).__init__(*args, **kwargs)

        self.fields['name'].widget.attrs.update(
            {
                'class': 'vTextField form-control text-capitalize',
                'placeholder': self.fields['name'].label,
                'required': True
            }
        )

        self.fields['email'].widget.attrs.update(
            {
                'class': 'vTextField form-control',
                'placeholder': 'name@example.com',
                'required': True
            }
        )

    def clean_name(self):
        return string_capitalize(self.cleaned_data['name'])

    class Meta:
        model = Newsletter
        fields = '__all__'

newsletter/views.py
from django.contrib import messages
from django.shortcuts import redirect, render
from utils.tools import string_capitalize

from newsletter.forms import NewsletterForm
from newsletter.models import Newsletter


def subscribe(request):
    """Renders the template corresponding to the newsletter user subscription form.

    (pt-BR) Renderiza o template correspondente ao formulário de inscrição
    do usuário na newsletter.

    Args:
        request (class): django.core.handlers.wsgi.WSGIRequest

    Returns:
        class: django.http.response.HttpResponse
    """

    form = NewsletterForm()
    return render(request, 'newsletter/subscribe.html', {'form': form})


def validate_subscribe(request):
    """Validates the user's subscription information for the newsletter.

    (pt_BR) Realiza a validação das informações de inscrição do usuário na
    newsletter.

    Args:
        request (class): django.core.handlers.wsgi.WSGIRequest

    Returns:
        class: django.http.response.HttpResponseRedirect
    """

    if request.method == 'POST':
        name = string_capitalize((request.POST.get('name')).strip())
        email = str(request.POST.get('email')).strip()

        if name and email:
            is_duplicated = True if len(Newsletter.objects.filter(
                email=email)) > 0 else False

            if not is_duplicated:
                try:
                    # Possible to refactor the code using the full_clean
                    # method to raise exceptions.
                    Newsletter(name=name, email=email).save()
                    level = messages.SUCCESS
                    message = 'E-mail cadastrado com sucesso! Obrigado por assinar \
                        nossa newsletter!'
                except Exception:
                    level = messages.ERROR
                    message = 'Erro inesperado ao realizar inscrição!'
            else:
                level = messages.INFO
                message = 'Muito obrigado pelo interesse! Seu email já está cadastrado \
                    para recebimento de nossa newsletter!'
        else:
            level = messages.WARNING
            message = 'Para assinar nossa newsletter, por favor forneça seu nome e \
                um endereço de email válido!'

        messages.add_message(request, level, message)

    return redirect('/newsletter')

newsletter/templates/newsletter/subscribe.html
{% extends 'base/index.html' %}

<!-- {% load static %} -->

<!-- {% block "style" %}{% endblock %} -->

{% block "title" %}Vitrine Digital{% endblock %}

{% block "nav_items" %}
    <li class="nav-item"><a href="{% url 'stores:choose-store' %}" class="nav-link">Início</a></li>
    <li class="nav-item"><a href="{% url 'newsletter:newsletter' %}" class="nav-link active">Newsletter</a></li>
    <li class="nav-item"><a href="{% url 'app:app_install' %}" class="nav-link" aria-current="page">Nosso App</a></li>
    <li class="nav-item"><a href="{% url 'about:about' %}" class="nav-link" aria-current="page">Sobre</a></li>
{% endblock %}

{% block "body" %}
    <!-- Inclusion of Bootstrap alert messages -->
    {% include "base/message.html" %}

    <div class="container col-xl-10 col-xxl-8 px-4 py-5">
        <div class="row align-items-center py-5">
            <div class="col-lg-7 text-center text-lg-start">
                <h1 class="display-4 fw-bold lh-1 mb-3">Assinando nossa newsletter...</h1>
                <p class="col-lg-10 fs-4">Você terá acesso em primeira mão aos lançamentos e novidades, as melhores ofertas e promoções das lojas participantes da Vitrine Digital. Não perca tempo! Cadastre-se!</p>
            </div>
            
            <div class="col-md-10 mx-auto col-lg-5">
                <form class="p-4 p-md-5 border rounded-3 bg-light" method="POST" action="{% url 'newsletter:validate_subscribe' %}">{% csrf_token %}
                    <div class="form-floating mb-3">
                        {% comment %} <input type="text" class="form-control text-capitalize" id="floatingName" placeholder="Nome completo" name="name" required>
                        <label for="floatingName">Nome completo</label> {% endcomment %}
                        {{ form.name }}
                        {{ form.name.label_tag }}
                    </div>
                    <div class="form-floating mb-3">
                        {% comment %} <input type="email" class="form-control" id="floatingInput" placeholder="name@example.com" name="email" required>
                        <label for="floatingInput">Endereço de email</label> {% endcomment %}
                        {{ form.email }}
                        {{ form.email.label_tag }}
                    </div>
                    <button class="w-100 btn btn-lg btn-primary" type="submit">Cadastre-se</button>
                    <hr class="my-4">
                    <small class="text-muted">Ao clicar em Cadastre-se, você concorda com os termos de uso.</small>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

<!-- {% block "social_media" %}{% endblock %} -->

{% block "script" %}
    <script src="{% static 'js/modal.alert.js' %}"></script>
{% endblock %}